[general]
data_root=/mnt/PREDiCTOR/PHOENIX
study=PREDiCTOR
self_heal=False
repo_root=/home/dpinterview
fake_root=/home/dpinterview/temp_root/PHOENIX

[postgresql]
host=localhost
port=5432
database=dpinterview
user=
password=

[openface_db]
host=localhost
port=5432
database=openface_db
user=
password=

[split-streams]
default_role=subject
left_role=subject
right_role=interviewer

[orchestration]
num_to_decrypt=5
openface_max_instances=3
snooze_time_seconds=900
pipeline_user=adamdavidson
pipeline_group=users

[openface]
openblas_num_threads=16
openface_max_retry=3

[openface_features]
int_cols=frame,face_id
bool_cols=success
time_cols=timestamp
sample_csv_file=/home/dpinterview/sample/openface/features.csv

[report_generation]
fau_h_gap_idx=5,9,14
bin_size=30
bins_per_page=60
report_version=v1.0.0
anonymize=False

[singularity]
singularity_image_path=/home/dpinterview/feature-extraction.sif
bind_params=/home/dpinterview/temp_root/PHOENIX:/home/dpinterview/temp_root/PHOENIX

[crawler]
hash_files=False
redcap_metadata_path=/mnt/PREDiCTOR/PHOENIX/PROTECTED/redcap_metadata.csv

[logging]
# supports relative paths from the repo root
# scripts
init_db=/mnt/PREDiCTOR/dpinterview_logs/init_db.log
import_study_metadata=/mnt/PREDiCTOR/dpinterview_logs/import_study_metadata.log
import_interview_files=/mnt/PREDiCTOR/dpinterview_logs/import_interview_files.log
import_audio_journals=/mnt/PREDiCTOR/dpinterview_logs/import_audio_journals.log

# runners
fetch_video=/mnt/PREDiCTOR/dpinterview_logs/01_fetch_video.log
metadata=/mnt/PREDiCTOR/dpinterview_logs/02_metadata.log
video-qqc=/mnt/PREDiCTOR/dpinterview_logs/03_video-qqc.log
split-streams=/mnt/PREDiCTOR/dpinterview_logs/04_split-streams.log
openface=/mnt/PREDiCTOR/dpinterview_logs/05_openface.log
openface_qc=/mnt/PREDiCTOR/dpinterview_logs/06_openface_qc.log
predictor-importer=/mnt/PREDiCTOR/dpinterview_logs/predictor-importer.log
predictor-exporter=/mnt/PREDiCTOR/dpinterview_logs/predictor-exporter.log
load_openface=/mnt/PREDiCTOR/dpinterview_logs/load_openface.log
pipeline.runners.predictor.face_pipe=/mnt/PREDiCTOR/dpinterview_logs/face_pipe.log
report_generation=/mnt/PREDiCTOR/dpinterview_logs/report_generation.log
pipeline.runners.study_specific.predictor.21_transcript_quick_qc = /mnt/PREDiCTOR/dpinterview_logs/21_transcript_quick_qc.log
